site_name: "Em Yêu Công Nghệ"
# permalink: /:title.html

# the subpath of your site, e.g. /blog
baseurl: "https://panadorado.github.io"
# the base hostname & protocol for your site, e.g. http://example.com
# url: "https://emyeucongnghe.tk"

gems: [jekyll-paginate, jekyll-paginate-category]

paginate: 6
paginate_path: "/page:num/"
category_layout: "index.html"
