site_name: "Công Nghệ Và Cuộc Sống"
# permalink: /:title.html

# the subpath of your site, e.g. /blog
base_url: "https://panadorado.github.io/"
# the base hostname & protocol for your site, e.g. http://example.com
url: "http://congnghevacuocsong.tk"

gems: [jekyll-paginate, jekyll-paginate-category]

paginate: 6
paginate_path: "/page:num/"
category_layout: "index.html"
